apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  labels:
    app: ping-pong
spec:
  selector:
    app: ping-pong
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
