apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: writer
          image: log-output-writer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_PATH
              value: /data/log.txt
            - name: INTERVAL
              value: "5"
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: reader
          image: log-output-reader:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_PATH
              value: /data/log.txt
            - name: PORT
              value: "8000"
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: shared-data
              mountPath: /data
